### ISSUE TITLE
Category doesn't appear to be an array

### ISSUE THREAD

**Issue by hlascelles** [kevyder/ruby_pagespeed_insights#3]
When using this tool it appears there is some change in the way `category` is handled.

In the example it is a string "seo":

```
request = PagespeedInsights::V5.new(
  url: 'http://site.com',
  key: 'your api key',
  strategy: 'desktop',
  categories: 'seo'
)
```

But the code expects an array. However, when using an array it is always ignored an "performance" is run.

Judging by [this answer](https://stackoverflow.com/a/54476309/1267203) it shouldn't be a csv, but a query array of lots of `category` values.

**Comment by kevyder** [comment]
the fix was released in version 1.2.0
